[package]
authors = ["Daniel Egger <daniel@eggers-club.de>"]
categories = [
    "embedded",
    "no-std",
]
keywords = [
    "arm",
    "cortex-m",
    "template",
]
name = "microbit"
version = "0.2.0"

[dependencies]
bare-metal = "0.1.1"
cortex-m = "0.4.2"
numtoa = "0.0.7"
static-ref = "0.2.1"
vcell = "0.1.0"
volatile-register = "0.2.0"

[dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.12"

[dependencies.nrf51]
features = ["rt"]
git = "https://github.com/therealprof/nrf51"

[dependencies.nrf51-hal]
features = ["rt"]
git = "https://github.com/therealprof/nrf51-hal"

[features]
default = ["rt"]
rt = []
[profile.dev]
debug = true
lto = true

[profile.release]
debug = true
lto = true
opt-level = "s"
