[alias]
xtask = "run --package xtask --"

[target.thumbv6m-none-eabi]
runner = 'probe-run --chip nRF51822_xxAA'
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[target.thumbv7em-none-eabihf]
# Execute binary using gdb when calling cargo run
runner = "probe-run --chip nRF52833_xxAA"
# Tweak to the linking process required by the cortex-m-rt crate
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]
